web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.homeserver.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.homeserver.com:9090'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '9090:9090'
    - '2224:22'
  volumes:
    - '/sdb/work/srv/gitlab/config:/etc/gitlab'
    - '/sdb/work/srv/gitlab/logs:/var/log/gitlab'
    - '/sdb/work/srv/gitlab/data:/var/opt/gitlab'
